### ISSUE TITLE
NodeSchool #10 in October

### ISSUE THREAD

**Issue by TimonVS** [nodeschool/rotterdam#3]
It's been a while, so I was thinking of organizing a meetup in October or November. 

I was thinking of doing a basic introduction to JavaScript and Node by one of us and afterwards attendees can pick up workshoppers or work on their own projects.

cc: @davidvanleeuwen @Tmw @jchn

**Comment by davidvanleeuwen** [comment]
Sounds like a plan! I'd like to help out too.

Somebody in the space suggested to do pixelflut with nodejs. That could be cool and interesting to learn some basic javascript.

**Comment by TimonVS** [comment]
> Somebody in the space suggested to do pixelflut with nodejs. That could be cool and interesting to learn some basic javascript.

Sounds cool! Maybe we can make it a focussed session for a future event? For this event I'd like to focus on JS and Node basics if you're alright with that, because it has been a very long time since we organized an event, lots of new people might join who have no JS/Node experience at all :)

What about the 22nd of October?

**Comment by davidvanleeuwen** [comment]
A bit of a late reply, but are you still up for this?

**Comment by VictorKoenders** [comment]
Nodeschool when?

**Comment by Nosfaratuss** [comment]
Nodeschool pls!

**Comment by TimonVS** [comment]
Sure, it's just a question of when. December is probably not a good idea because it's a very busy month, can we still do it in November? Like maybe the 26th, 28th or 29th?

**Comment by Nosfaratuss** [comment]
28 and 29 November could work for me. December could be an option but not for the weekends.

**Comment by davidvanleeuwen** [comment]
I'm fine with both dates 👍
